### ISSUE TITLE
Updating Website's Look + FE Dependencies 

### ISSUE THREAD

**Issue by mattxwang** [scifio/scifio.github.io#3]
As @ctrueden [asked](https://github.com/fiji/fiji.github.io/issues/2), I can do a similar process to what I've done with the Fiji website:
* Update Bootstrap, jQuery, and any other dependencies
* Make website mobile friendly - e.g. "Bioformats" image is cut-off on small screen sizes
* Add a few icons to navigational content on the website
* Add a README for incoming contributors

This one shouldn't be as time-consuming as the Fiji website, since this website is pretty simple. What are your thoughts @ctrueden ?

**Comment by ctrueden** [comment]
Sounds great, @malsf21! I agree this site should be very straightforward.

**Comment by mattxwang** [comment]
Pushed a PR to #4.

Also, have you had time to look at the Fiji PR?

**Comment by ctrueden** [comment]
Fixed by #4!
